def build_report(inputs: dict, outputs: dict) -> str:
    sequence_lines = "\n\n".join(f"### {label}\n{message}" for label, message in outputs["sequence"].items())
    return f"""# FollowUpPilot AI Follow-Up Plan

## Customer
Customer: {inputs['customer'] or 'N/A'}
Company: {inputs['company'] or 'N/A'}
Project Type: {inputs['project_type']}
Lead Status: {inputs['lead_status']}
Lead Temperature: {outputs['temperature']}
Deal Risk: {outputs['deal_risk']}
Main Risk: {outputs['main_risk']}
Priority: {outputs['priority']}
Priority Score: {outputs['score']}
Recommended Timing: {outputs['timing']}
Next Best Action: {outputs['next_action']}

## Why This Recommendation
{outputs['why']}

## Text Message
{outputs['sms']}

## Email
Subject: {outputs['subject']}

{outputs['email']}

## Voicemail Script
{outputs['voicemail']}

## CRM Note
{outputs['crm']}

## Call Script
{outputs['call']}

## Objection Guidance
{outputs['guidance']}

## Manager Coaching Note
{outputs['coaching']}

## Follow-Up Sequence

{sequence_lines}

---

Generated by FollowUpPilot AI.
"""
