from __future__ import annotations

from typing import Any


def build_report(inputs: dict[str, Any], outputs: dict[str, Any]) -> str:
    if not outputs:
        raise ValueError("No follow-up outputs were provided.")

    sequence = outputs.get("sequence") or {}
    sequence_lines = "\n\n".join(
        f"### {_safe(label)}\n{_safe(message)}" for label, message in sequence.items()
    )
    suggested_date = outputs.get("suggested_followup_date") or "N/A"
    followup_status = outputs.get("followup_status") or "N/A"
    return f"""# FollowUpPilot AI Follow-Up Plan

## Customer
Customer: {_field(inputs, "customer_name", "customer")}
Company: {_field(inputs, "company_name", "company")}
Service Type: {_field(inputs, "service_type", "project_type")}
Lead Stage: {_field(inputs, "lead_stage", "lead_status")}
Assigned Rep: {_field(inputs, "assigned_rep")}
Lead Temperature: {_field(outputs, "temperature")}
Deal Risk: {_field(outputs, "deal_risk")}
Main Risk: {_field(outputs, "main_risk")}
Priority: {_field(outputs, "priority")}
Priority Score: {_field(outputs, "score")}
Recommended Timing: {_field(outputs, "timing")}
Suggested Follow-Up Date: {_safe(suggested_date)}
Follow-Up Status: {_safe(followup_status)}
Next Best Action: {_field(outputs, "next_action")}

## Why This Recommendation
{_field(outputs, "why")}

## Text Message
{_field(outputs, "sms")}

## Email
Subject: {_field(outputs, "subject")}

{_field(outputs, "email")}

## Voicemail Script
{_field(outputs, "voicemail")}

## CRM Note
{_field(outputs, "crm")}

## Call Script
{_field(outputs, "call")}

## Objection Guidance
{_field(outputs, "guidance")}

## Manager Coaching Note
{_field(outputs, "coaching")}

## Follow-Up Sequence

{sequence_lines or "No active follow-up sequence."}

---

Generated by FollowUpPilot AI.
"""


def _field(payload: dict[str, Any], *keys: str) -> str:
    for key in keys:
        value = payload.get(key)
        if value not in (None, ""):
            return _safe(value)
    return "N/A"


def _safe(value: Any) -> str:
    return str(value).replace("\x00", "").strip() or "N/A"
